server:
  port: 3302

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hom1db?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 60000
    password:
    jedis:
      pool:
        minIdle: 1
        maxIdle: 300
        maxWait: -1
        maxActive: 8

qiniu:
  qiniu_access_key: fflJ8zBJwUJpDRzLuQbddw5BB_1tdIXQuvXM7t_b
  qiniu_secret_key: 8vGtdr_knUcvAI8aqzTEtAmczTkYLo26OVq6L_rG
  qiniu_domain: http://img.168dh.cn
  qiniu_bucket: img-dh
  qiniu_small_url:

admin:
  domain: http://localhost:8080
  username: iksen
  password: iksen22.